### ISSUE TITLE
YouTube videos default to opening in in-app safari

### ISSUE THREAD

**Issue by ericschmar** [christianselig/apollo-bugs#1318]
When browsing on Home, tapping a YouTube video now defaults to opening in the in-app safari app, instead of the in-app video player. This really sucks, mostly because there are ads in the videos now, and the controls are worse.

**Comment by pickle-pot** [comment]
Appears to be a duplicate of issue #1301

**Comment by iphizzle** [comment]
this has been happening to me for like a month. it won’t even let me hold down on the video to press “open in youtube.” as soon as the thumbnail is touched, it goes straight to the in-app safari. :/ 

edit:
and it’s not even the ads i’m thinking about. i have an ad blocker on youtube, anyway. i just want to at least be able to click, “open in youtube.” it’s really annoying having to open in-app safari youtube

**Comment by pico0102** [comment]
Not a duplicate issue. This issue is about the video not playing in the Apollo app native video player. It now either opens the YouTube app or plays in safari

**Comment by iphizzle** [comment]
this was fixed like forever ago, so i don’t know what you mean

**Comment by pico0102** [comment]
Well it’s marked as open and the issue persists for me, so how can I help?
